# Generated by Django 2.2.5 on 2020-01-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='kcal',
            field=models.IntegerField(default=0),
        ),
    ]
