# Generated by Django 2.2.5 on 2019-12-01 08:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='src',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
