# Generated by Django 2.2.5 on 2020-01-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191201_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img2',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='img3',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='img4',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='img5',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
